import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "@/libs/components/global/Navbar/Navbar";
import Footer from "@/libs/components/global/Footer/Footer";
import AntdProvider from "@/libs/components/global/AntdProvider/AntdProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`}>
        <AntdProvider>
          <main className="w-full mx-auto">
            <Navbar />
            <div className="py-10 h-screen">{children}</div>
            <Footer />
          </main>
        </AntdProvider>
      </body>
    </html>
  );
}
